name: CI Build

on:
  push: 
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  test:
    name: Run Tests and Quality Checks
    runs-on: ubuntu-latest
    container: python:3.9-slim

    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017
        options: --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")'" --health-interval=10s --health-timeout=5s --health-retries=5

    env:
      DATABASE_URI: mongodb://mongo:27017
      TEST_DATABASE_NAME: ${{ vars.TEST_DATABASE_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt
      
      - name: Lint with flake8
        run: |
          flake8 app --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 app --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Run unit tests with Pytest
        run: pytest


  build:
    name: Build and Push Docker image
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    env:
      IMAGE_NAME: ${{ vars.DOCKER_USERNAME }}/notif-srv
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Validate Context
        uses: docker/build-push-action@v6
        with:
          call: check
          context: .
          file: ./Dockerfile

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}

